# Generated by Django 4.2.5 on 2023-09-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='timeCreated',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
